# @package _global_
# Local launcher configuration (no SLURM)

defaults:
  - override /hydra/launcher: basic

wandb:
  enabled: False
  config:
    entity: lewm
    project: lewm
    name: ${name}
    id: ${name}
    resume: allow
    log_model: False